/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Blob {
    id?: string;

    creationDate?: number;

    size?: number;

    hashMd5?: string;

    status?: Blob.StatusEnum;

    storageUnitId?: string;

}
export namespace Blob {
    export enum StatusEnum {
        CREATING = <any> 'CREATING',
        PARTIAL = <any> 'PARTIAL',
        LOCKED = <any> 'LOCKED'
    }
}
