/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface BoolQuery extends models.Query {
    mustClauses?: Array<models.Query>;

    mustNotClauses?: Array<models.Query>;

    shouldClauses?: Array<models.Query>;

    minimumShouldMatch?: number;

}
