/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ExportSpec {
    query?: models.Query;

    rootTenantId?: string;

    searchMode?: ExportSpec.SearchModeEnum;

    storageUnitId?: string;

    type?: string;

	excludedTenants?: string[]

	exportEmptyTenants?: boolean

	excludedEntityTypes?: string[]

	excludedItemTypes?: string[]

}
export namespace ExportSpec {
    export enum SearchModeEnum {
        DEFAULT = <any> 'DEFAULT',
        TRASH = <any> 'TRASH',
        ALL = <any> 'ALL'
    }
}
