/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Grants {
    id?: string;

    grants?: Array<Grants.GrantsEnum>;

    fieldGrants?: { [key: string]: Array<string>; };

}
export namespace Grants {
    export enum GrantsEnum {
        AUTHENTICATE = <any> 'AUTHENTICATE',
        ADMIN = <any> 'ADMIN',
        UPLOAD = <any> 'UPLOAD',
        TYPESEARCH = <any> 'TYPE_SEARCH',
        ENTITYVIEW = <any> 'ENTITY_VIEW',
        ENTITYCREATE = <any> 'ENTITY_CREATE',
        ENTITYEDIT = <any> 'ENTITY_EDIT',
        ENTITYDELETE = <any> 'ENTITY_DELETE',
        ITEMVIEW = <any> 'ITEM_VIEW',
        ITEMCREATE = <any> 'ITEM_CREATE',
        ITEMEDIT = <any> 'ITEM_EDIT',
        ITEMDELETE = <any> 'ITEM_DELETE',
        ITEMPUBLISH = <any> 'ITEM_PUBLISH',
        ITEMBROADCAST = <any> 'ITEM_BROADCAST',
        FILEDOWNLOAD = <any> 'FILE_DOWNLOAD',
        FIELDVIEW = <any> 'FIELD_VIEW',
        FIELDEDIT = <any> 'FIELD_EDIT'
    }
    export enum FieldGrantsEnum {
        AUTHENTICATE = <any> 'AUTHENTICATE',
        ADMIN = <any> 'ADMIN',
        UPLOAD = <any> 'UPLOAD',
        TYPESEARCH = <any> 'TYPE_SEARCH',
        ENTITYVIEW = <any> 'ENTITY_VIEW',
        ENTITYCREATE = <any> 'ENTITY_CREATE',
        ENTITYEDIT = <any> 'ENTITY_EDIT',
        ENTITYDELETE = <any> 'ENTITY_DELETE',
        ITEMVIEW = <any> 'ITEM_VIEW',
        ITEMCREATE = <any> 'ITEM_CREATE',
        ITEMEDIT = <any> 'ITEM_EDIT',
        ITEMDELETE = <any> 'ITEM_DELETE',
        ITEMPUBLISH = <any> 'ITEM_PUBLISH',
        ITEMBROADCAST = <any> 'ITEM_BROADCAST',
        FILEDOWNLOAD = <any> 'FILE_DOWNLOAD',
        FIELDVIEW = <any> 'FIELD_VIEW',
        FIELDEDIT = <any> 'FIELD_EDIT'
    }
}
