/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface OwnTenantEntityFilter extends models.EntityFilter {
    mode?: OwnTenantEntityFilter.ModeEnum;

}
export namespace OwnTenantEntityFilter {
    export enum ModeEnum {
        OWN = <any> 'OWN',
        OWNANDCHILDREN = <any> 'OWN_AND_CHILDREN',
        OWNANDPARENTS = <any> 'OWN_AND_PARENTS',
        OWNANDPARENTANDCHILDREN = <any> 'OWN_AND_PARENT_AND_CHILDREN',
        CHILDREN = <any> 'CHILDREN',
        PARENTS = <any> 'PARENTS',
        PARENTSANDCHILDREN = <any> 'PARENTS_AND_CHILDREN'
    }
}
