/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Publication {
    id?: string;

    token?: string;

    scheme?: string;

    fileTypes?: Array<string>;

    creationDate?: models.Date;

    startValidityDate?: models.Date;

    endValidityDate?: models.Date;

    accessDate?: models.Date;

    accessCount?: number;

    accessMax?: number;

    item?: string;

}
