/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface TaskExecution {
    taskId?: string;

    groupId?: string;

    completed?: boolean;

    submitionDate?: number;

    completionDate?: number;

    stepsCount?: number;

    stepsDone?: number;

    error?: string;

    taskResult?: any;

    progressMessage?: string;

    progressPercent?: number;

}
