/**
 * Ozone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Tenant {
    id?: string;

    parentId?: string;

    identifier: string;

    grants?: Array<models.Permission>;

    revokes?: Array<models.Permission>;

    scopes?: Array<models.Permission>;

    parentScopes?: Array<models.Permission>;

    parentGrants?: Array<models.Permission>;

    parentRevokes?: Array<models.Permission>;

    childrenScopes?: Array<models.Permission>;

    childrenGrants?: Array<models.Permission>;

    childrenRevokes?: Array<models.Permission>;

}
